import { markets, type Market } from "@/lib/markets";
import { useEffect,useState,type FormEvent,type ReactNode } from "react";
import { labels, type Section } from "./admin-shared";

export function AdminLogin({ email, password, error, busy, setEmail, setPassword, signIn }: { email: string; password: string; error: string; busy: boolean; setEmail: (value: string) => void; setPassword: (value: string) => void; signIn: (event: FormEvent<HTMLFormElement>) => void | Promise<void> }) {
  return <main className="cms-login"><form className="cms-login-card" onSubmit={signIn}>
    <img src="/envol-logo-transparent.png" alt="Envol des Enfants" /><span className="cms-eyebrow">Espace de gestion sécurisé</span><h1>Votre boutique,<br /><em>au bout des doigts.</em></h1><p>Connectez-vous pour gérer vos produits, vos commandes et vos promotions.</p>
    {error && <div className="cms-error">{error}</div>}
    <label>Adresse courriel<input type="email" autoComplete="username" value={email} onChange={(event) => setEmail(event.target.value)} required /></label>
    <label>Mot de passe<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>
    <button disabled={busy}>{busy ? "Connexion…" : "Accéder à mon administration →"}</button><a href="/">← Retour à la boutique</a>
  </form></main>;
}

export function AdminLayout({ admin, section, market, notice, error, notificationCount = 0, onSection, onMarket, signOut, children }: { admin: { email: string; name: string }; section: Section; market: Market; notice: string; error: string; notificationCount?: number; onSection: (section: Section) => void; onMarket: (market: Market) => void; signOut: () => void; children: ReactNode }) {
  type HistoryAction={key:string;type:string;label:string;state:"applied"|"restored";updated_at?:string};
  const [historyActions,setHistoryActions]=useState<HistoryAction[]>([]);const [undoBusy,setUndoBusy]=useState("");const [theme,setTheme]=useState<"light"|"dark">("dark");
  useEffect(()=>{const saved=window.localStorage.getItem("cms-theme");const next=saved==="light"||saved==="dark"?saved:(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light");setTheme(next);document.documentElement.dataset.cmsTheme=next},[]);
  const toggleTheme=()=>{const next=theme==="dark"?"light":"dark";setTheme(next);window.localStorage.setItem("cms-theme",next);document.documentElement.dataset.cmsTheme=next};
  const refreshUndo=()=>fetch("/api/admin/history").then(r=>r.json()).then(d=>setHistoryActions(Array.isArray(d.actions)?d.actions:[])).catch(()=>{});
  useEffect(()=>{refreshUndo();const id=window.setInterval(refreshUndo,3000);return()=>window.clearInterval(id)},[section]);
  const undo=async(action:HistoryAction)=>{if(!action?.key||undoBusy)return;setUndoBusy(action.key);try{const r=await fetch("/api/admin/history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({key:action.key})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Restauration impossible.");await refreshUndo();window.location.reload()}catch(e){window.alert(e instanceof Error?e.message:"Restauration impossible.")}finally{setUndoBusy("")}};

  const icons: Record<Section, string> = { dashboard: "◉", products: "▣", stock: "▤", orders: "☷", customers: "♙", promotions: "✦", subscribers: "♡", advisor: "✧", notifications: "!", editor: "✎", settings: "⚙" };
  return <main className="cms-app">
    <aside className="cms-sidebar"><a className="cms-logo" href="/"><img src="/envol-logo-transparent.png" alt="Envol des Enfants" /></a><span className="cms-eyebrow">Administration</span><nav>{(Object.keys(labels) as Section[]).map((key) => <button key={key} className={section === key ? "active" : ""} onClick={() => onSection(key)}><span>{icons[key]}</span>{labels[key]}{key === "notifications" && notificationCount > 0 && <b className="cms-nav-badge">{notificationCount > 99 ? "99+" : notificationCount}</b>}</button>)}</nav><div className="cms-account"><strong>{admin.name}</strong><small>{admin.email}</small><button onClick={signOut}>Déconnexion</button></div></aside>
    <div className="cms-main"><header className="cms-topbar" ><div><span className="cms-eyebrow">Envol des Enfants · {markets[market].label}</span><h1>{labels[section]}</h1></div><div className="cms-top-actions"><button type="button" className="cms-theme-toggle" onClick={toggleTheme} aria-label={theme==="dark"?"Passer au mode clair":"Passer au mode sombre"} title={theme==="dark"?"Mode clair":"Mode sombre"}>{theme==="dark"?"☀ Clair":"☾ Sombre"}</button><details className="cms-history-menu"><summary className="cms-secondary cms-global-undo"><span aria-hidden="true">↶</span><span><strong>Historique des modifications</strong><small>${historyActions.length} action${historyActions.length===1?"":"s"} disponible${historyActions.length===1?"":"s"}</small></span><span className="cms-history-chevron">▾</span></summary><div className="cms-history-dropdown"><div className="cms-history-head"><strong>20 dernières modifications</strong><small>Restaure uniquement l’action choisie</small></div>{historyActions.length?historyActions.map((action,index)=><button key={action.key} type="button" className={`cms-history-item ${action.state==="restored"?"is-restored":""}`} disabled={undoBusy===action.key} onClick={()=>void undo(action)}><span className="cms-history-index">{index+1}</span><span className="cms-history-copy"><strong>{action.label}</strong><small>{action.state==="restored"?"↷ Restaurée · cliquer pour réappliquer":"↶ Cliquer pour restaurer cette action seulement"}</small></span><span>{undoBusy===action.key?"⌛":action.state==="restored"?"↷":"↶"}</span></button>):<p className="cms-history-empty">Aucune modification à restaurer.</p>}</div></details><div className="cms-market-switch" role="group" aria-label="Choisir la boutique"><button className={market === "conakry" ? "active" : ""} onClick={() => onMarket("conakry")}>Conakry · GNF</button><button className={market === "qc" ? "active" : ""} onClick={() => onMarket("qc")}>Québec · CAD</button></div><a href={`/?region=${market}`} target="_blank">Voir la boutique ↗</a></div></header>
      <div style={{height:96}} aria-hidden="true" />{notice && <div className="cms-notice">✓ {notice}</div>}{error && <div className="cms-error">{error}</div>}{children}
      <footer className="cms-footer"><span>Une création de <strong>AIP · Atelier Informatique Potvin</strong></span><span>© {new Date().getFullYear()} Envol des Enfants · Tous droits réservés.</span></footer>\n      <div className="cms-quick-scroll" aria-label="Défilement rapide"><button type="button" aria-label="Revenir complètement en haut" title="Retour en haut" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>↑</button><button type="button" aria-label="Aller complètement en bas" title="Aller en bas" onClick={() => window.scrollTo({ top: document.documentElement.scrollHeight, behavior: "smooth" })}>↓</button></div>
    </div>
  </main>;
}
