"use client";

import { useMemo, useState } from "react";
import { categories, request, type Row } from "./admin-shared";
import type { Market } from "@/lib/markets";

type Item={id:string;file:File;preview:string;hash:string;visualHash:string;duplicate:boolean;duplicateKind?:"exact"|"visual";url?:string;suggestion?:Row;group?:string;state:"ready"|"uploading"|"analyzing"|"done"|"error";error?:string};

async function sha256(file:File){const d=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function visualHash(file:File){const bitmap=await createImageBitmap(file);const canvas=document.createElement("canvas");canvas.width=16;canvas.height=16;const ctx=canvas.getContext("2d")!;ctx.drawImage(bitmap,0,0,16,16);bitmap.close();const data=ctx.getImageData(0,0,16,16).data;const lum:number[]=[];for(let i=0;i<data.length;i+=4)lum.push(Math.round(data[i]*.299+data[i+1]*.587+data[i+2]*.114));const avg=lum.reduce((a,b)=>a+b,0)/lum.length;return lum.map(v=>v>=avg?"1":"0").join("")}
async function prepareUpload(file:File){
 const target=900*1024,max=1600;
 const bitmap=await createImageBitmap(file);
 const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));
 const canvas=document.createElement("canvas");
 canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
 const ctx=canvas.getContext("2d");if(!ctx){bitmap.close();throw new Error("Impossible de préparer cette image.")}
 ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 let quality=.82,blob:Blob|null=null;
 do{blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",quality));quality-=.08}while(blob&&blob.size>target&&quality>=.42);
 if(!blob)throw new Error("Impossible de compresser cette image.");
 if(blob.size>target)throw new Error("Cette image reste trop volumineuse après compression.");
 return new File([blob],file.name.replace(/\.[^.]+$/,"")+".jpg",{type:"image/jpeg",lastModified:Date.now()});
}
function distance(a:string,b:string){let n=0;for(let i=0;i<Math.min(a.length,b.length);i++)if(a[i]!==b[i])n++;return n+Math.abs(a.length-b.length)}
function norm(v:unknown){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function groupKey(s:Row){const brand=norm(s.brand);const name=norm(s.name_fr).split(" ").filter(x=>x.length>2).slice(0,5).join("-");return `${norm(s.category)}|${brand}|${name}`}

export function AiBatchImport({market,busy,onDone}:{market:Market;busy:boolean;onDone:()=>Promise<void>}){
 const[items,setItems]=useState<Item[]>([]);const[working,setWorking]=useState(false);const[standby,setStandby]=useState(true);const unique=useMemo(()=>items.filter(i=>!i.duplicate),[items]);
 async function choose(files:FileList|null){const selected=Array.from(files||[]).filter(f=>f.type.startsWith("image/"));const seen=new Set<string>();const visual:string[]=[];const next:Item[]=[];
  for(const file of selected){const hash=await sha256(file),vh=await visualHash(file);const exact=seen.has(hash);const near=!exact&&visual.some(x=>distance(x,vh)<=18);seen.add(hash);if(!exact&&!near)visual.push(vh);next.push({id:crypto.randomUUID(),file,preview:URL.createObjectURL(file),hash,visualHash:vh,duplicate:exact||near,duplicateKind:exact?"exact":near?"visual":undefined,state:"ready"})}setItems(next)}
 async function analyzeAll(){setWorking(true);for(const item of unique){try{setItems(a=>a.map(x=>x.id===item.id?{...x,state:"uploading"}:x));const prepared=await prepareUpload(item.file);const data=new FormData();data.append("file",prepared);const uploaded=await request("/api/admin/upload",{method:"POST",body:data});const url=String(uploaded.url||"");setItems(a=>a.map(x=>x.id===item.id?{...x,url,state:"analyzing"}:x));const result=await request("/api/admin/analyze-product",{method:"POST",body:JSON.stringify({image_url:url})});const suggestion=result.suggestion as Row;const done={...item,url,suggestion,group:groupKey(suggestion),state:"done" as const};setItems(a=>a.map(x=>x.id===item.id?done:x))}catch(error){setItems(a=>a.map(x=>x.id===item.id?{...x,state:"error",error:error instanceof Error?error.message:"Erreur"}:x))}}setWorking(false)}
 function update(id:string,field:string,value:string){setItems(a=>a.map(i=>i.id===id&&i.suggestion?{...i,suggestion:{...i.suggestion,[field]:value},group:groupKey({...i.suggestion,[field]:value})}:i))}
 async function createAll(){setWorking(true);try{const done=items.filter(x=>!x.duplicate&&x.state==="done"&&x.suggestion&&x.url);const groups=new Map<string,Item[]>();for(const item of done){const key=item.group||item.id;groups.set(key,[...(groups.get(key)||[]),item])}for(const group of groups.values()){const first=group[0];const urls=group.map(x=>x.url!).filter(Boolean);await request("/api/admin/products",{method:"POST",body:JSON.stringify({...first.suggestion,image_url:urls[0],images_json:JSON.stringify(urls.slice(1)),price_qc:0,price_conakry:0,stock_qc:0,stock_conakry:0,visible_qc:!standby&&market==="qc",visible_conakry:!standby&&market==="conakry",status:"available"})})}await onDone();setItems([])}finally{setWorking(false)}}
 const duplicates=items.filter(i=>i.duplicate).length,ready=items.filter(i=>!i.duplicate&&i.state==="done").length,groups=new Set(items.filter(i=>i.group).map(i=>i.group)).size;
 return <section className="cms-ai-batch"><div className="cms-ai-batch-head"><div><h3>Analyse des produits par IA</h3><p>Balancez un lot de photos : l’IA détecte les doublons, regroupe les vues d’un même produit et prépare des fiches FR/EN complètes à vérifier avant enregistrement.</p></div><label className="cms-primary cms-ai-file">Choisir des photos<input type="file" accept="image/*" multiple disabled={busy||working} onChange={e=>void choose(e.target.files)}/></label></div>{items.length>0&&<><div className="cms-ai-summary"><strong>{items.length}</strong> image(s) · <strong>{duplicates}</strong> doublon(s) éliminé(s) · <strong>{unique.length}</strong> à analyser · <strong>{groups}</strong> produit(s) regroupé(s) · <strong>{ready}</strong> image(s) prête(s)</div><div className="cms-ai-grid">{items.map(item=><article key={item.id} className={item.duplicate?"is-duplicate":""}><img src={item.preview} alt=""/><div><strong>{item.file.name}</strong>{item.duplicate?<span>{item.duplicateKind==="exact"?"Doublon exact":"Doublon visuel probable"} — ignoré</span>:item.suggestion?<><input value={String(item.suggestion.name_fr||"")} onChange={e=>update(item.id,"name_fr",e.target.value)}/><select value={String(item.suggestion.category||"eveil")} onChange={e=>update(item.id,"category",e.target.value)}>{Object.entries(categories).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><textarea value={String(item.suggestion.description_fr||"")} onChange={e=>update(item.id,"description_fr",e.target.value)}/><small>{item.group&&items.filter(x=>x.group===item.group).length>1?`Même produit : ${items.filter(x=>x.group===item.group).length} photos`:"Produit unique"} · EN : {String(item.suggestion.description_en||"")}</small></>:<span>{item.state==="error"?item.error:item.state==="ready"?"Prête à analyser":"Analyse en cours…"}</span>}</div></article>)}</div><label className="cms-ai-standby"><input type="checkbox" checked={standby} onChange={e=>setStandby(e.target.checked)}/><span><strong>Mettre les nouveaux produits en attente</strong><small>Les fiches seront enregistrées dans le CMS, mais resteront masquées du site jusqu’à leur activation.</small></span></label><div className="cms-ai-actions"><button className="cms-secondary" disabled={working||unique.length===0} onClick={()=>void analyzeAll()}>Analyser avec l’IA</button><button className="cms-primary" disabled={working||ready===0} onClick={()=>void createAll()}>{standby?"Enregistrer les fiches en attente":"Enregistrer et afficher les produits"}</button></div></>}</section>
}
