import type { Product } from "./default-catalog";

type MamaItem = [string, string, string, string, string?];

const items: MamaItem[] = [
  ["Poupée mode en robe argentée", "Fashion doll in silver dress", "poupees", "Poupée mode"],
  ["Poupée Karma's World · Winston", "Karma's World Winston doll", "poupees", "Karma's World"],
  ["Disney Moana 2 · ensemble de poupées", "Disney Moana 2 doll set", "disney", "Disney Moana 2"],
  ["Disney Moana 2 · poupée d'aventure", "Disney Moana 2 adventure doll", "disney", "Disney Moana 2"],
  ["Poupée garçon My Life · tenue sportive", "My Life boy doll · sporty outfit", "poupees", "My Life As"],
  ["LOL Surprise Boys · Arcade Heroes", "LOL Surprise Boys · Arcade Heroes", "poupees", "LOL Surprise"],
  ["Disney Encanto · poupée Bruno", "Disney Encanto Bruno doll", "disney", "Disney Encanto"],
  ["Disney Raya · poupée guerrière", "Disney Raya warrior doll", "disney", "Disney Raya"],
  ["Rainbow High · poupée et accessoires", "Rainbow High doll and accessories", "poupees", "Rainbow High"],
  ["Miraculous · poupée Chat Noir", "Miraculous Cat Noir doll", "poupees", "Miraculous"],
  ["My Life · ensemble de perles arc-en-ciel", "My Life rainbow bead set", "poupees", "My Life As"],
  ["My Sweet Baby · accessoires pour poupée", "My Sweet Baby doll accessories", "poupees", "My Sweet Baby"],
  ["Hairmazing · poupées Bella et Harmoni", "Hairmazing Bella and Harmoni dolls", "poupees", "Hairmazing"],
  ["Poupée My Life · tenue décontractée", "My Life doll · casual outfit", "poupees", "My Life As"],
  ["My Life · appareil photo et accessoires", "My Life camera and accessories", "poupees", "My Life As"],
  ["Miraculous · poupée Rena Rouge", "Miraculous Rena Rouge doll", "poupees", "Miraculous"],
  ["My Life · lunettes cœur et accessoires", "My Life heart glasses and accessories", "poupees", "My Life As"],
  ["Miraculous · ensemble de figurines", "Miraculous figure set", "poupees", "Miraculous"],
  ["Miraculous · poupée Vesperia", "Miraculous Vesperia doll", "poupees", "Miraculous"],
  ["Disney Encanto · poupée Luisa", "Disney Encanto Luisa doll", "disney", "Disney Encanto"],
  ["Shadow High · ensemble beauté", "Shadow High beauty set", "poupees", "Shadow High"],
  ["Poupée My Life · blonde avec lunettes", "My Life blonde doll with glasses", "poupees", "My Life As"],
  ["LOL OMG Remix · poupée Pop B.B.", "LOL OMG Remix Pop B.B. doll", "poupees", "LOL OMG"],
  ["Miraculous · duo de figurines", "Miraculous two-figure set", "poupees", "Miraculous"],
  ["LOL OMG Fierce · poupée Lady Diva", "LOL OMG Fierce Lady Diva doll", "poupees", "LOL OMG"],
  ["Petite poupée bébé", "Little baby doll", "poupees", "Poupée bébé"],
  ["Rainbow High Junior · poupée violette", "Rainbow High Junior purple doll", "poupees", "Rainbow High"],
  ["Poupée sirène My Life", "My Life mermaid doll", "poupees", "My Life As"],
  ["Glamour Girl · poupée princesse", "Glamour Girl princess doll", "poupees", "Glamour Girl"],
  ["Baby Alive · ensemble de deux poupées", "Baby Alive two-doll set", "poupees", "Baby Alive"],
  ["Rainbow High · poupée en tenue orange", "Rainbow High doll in orange outfit", "poupees", "Rainbow High"],
  ["Poupée Baby Alive", "Baby Alive doll", "poupees", "Baby Alive"],
  ["Baby Alive · ensemble pâtisserie", "Baby Alive baking set", "poupees", "Baby Alive"],
  ["My Life · sac et lunettes de soleil", "My Life bag and sunglasses", "poupees", "My Life As"],
  ["Miraculous · trio de figurines", "Miraculous three-figure set", "poupees", "Miraculous"],
  ["Poupée bébé My Life · robe rose", "My Life baby doll · pink dress", "poupees", "My Life As"],
  ["Disney Encanto · poupée Mirabel", "Disney Encanto Mirabel doll", "disney", "Disney Encanto"],
  ["Glamour Girl · princesse blonde", "Glamour Girl blonde princess", "poupees", "Glamour Girl"],
  ["Disney Aladdin · poupée Génie", "Disney Aladdin Genie doll", "disney", "Disney Aladdin"],
  ["LOL OMG Remix · poupée Lonestar", "LOL OMG Remix Lonestar doll", "poupees", "LOL OMG"],
  ["Miraculous · poupée Ladybug", "Miraculous Ladybug doll", "poupees", "Miraculous"],
  ["Disney Encanto · poupée Mirabel en robe", "Disney Encanto Mirabel dress doll", "disney", "Disney Encanto"],
  ["Hairmazing · poupée Dee Dee", "Hairmazing Dee Dee doll", "poupees", "Hairmazing"],
  ["LOL OMG Remix · poupée Kitty K", "LOL OMG Remix Kitty K doll", "poupees", "LOL OMG"],
  ["Disney Princesses · ensemble Moana", "Disney Princess Moana set", "disney", "Disney Princess"],
  ["Petite poupée Baby Alive", "Little Baby Alive doll", "poupees", "Baby Alive"],
  ["LOL OMG Fierce · poupée de mode", "LOL OMG Fierce fashion doll", "poupees", "LOL OMG"],
  ["My Sweet Baby · ensemble de bain", "My Sweet Baby bath set", "poupees", "My Sweet Baby"],
  ["Rainbow High Pacific Coast · poupée", "Rainbow High Pacific Coast doll", "poupees", "Rainbow High"],
  ["Poupée My Life · écolière", "My Life schoolgirl doll", "poupees", "My Life As"],
  ["Miraculous · poupée renarde", "Miraculous fox hero doll", "poupees", "Miraculous"],
  ["Disney La Petite Sirène · poupée Ursula", "Disney The Little Mermaid Ursula doll", "disney", "Disney Princess"],
  ["Disney La Petite Sirène · ensemble de poupées", "Disney The Little Mermaid doll set", "disney", "Disney Princess"],
  ["Disney Encanto · poupée Isabela et accessoires", "Disney Encanto Isabela doll and accessories", "disney", "Disney Encanto"],
  ["Poupée rousse en tenue d'automne", "Red-haired doll in autumn outfit", "poupees", "Poupée mode"],
  ["Poupée Karma's World", "Karma's World doll", "poupees", "Karma's World"],
  ["Ensemble coiffure pour poupée", "Doll styling set", "poupees", "Poupée mode"],
  ["Miraculous · poupée Bunnyx", "Miraculous Bunnyx doll", "poupees", "Miraculous"],
  ["My Life · chaussures roses", "My Life pink shoes", "poupees", "My Life As"],
  ["My Life · mini-figurines de héros", "My Life hero mini figures", "poupees", "My Life As"],
  ["My Life · ensemble de cuisine", "My Life kitchen set", "poupees", "My Life As"],
  ["Disney Princesses · tête à coiffer Raiponce", "Disney Princess Rapunzel styling head", "disney", "Disney Princess"],
  ["Ensemble épicerie pour poupée", "Doll grocery set", "poupees", "Poupée mode"],
];

export const mamaProducts: Product[] = items.map(([fr, en, category, brand], index) => ({
  id: `mama-${String(index + 1).padStart(2, "0")}`,
  name: { fr, en },
  category,
  brand,
  price: 0,
  priceConakry: 0,
  priceQc: 0,
  stockConakry: 1,
  stockQc: 1,
  visibleConakry: true,
  visibleQc: true,
  ages: "3+",
  sheet: "",
  position: 0,
  imageUrl: `/products/poupees-mama/mama-${String(index + 1).padStart(2, "0")}.webp`,
  status: "available",
  badge: "new",
  detail: {
    fr: category === "disney" ? "Poupée ou accessoire de princesse Disney." : "Poupée ou accessoire pour enrichir les histoires et le jeu imaginatif.",
    en: category === "disney" ? "Disney princess doll or accessory." : "Doll or accessory for imaginative storytelling and play.",
  },
}));
