import type { Product } from "./default-catalog";

export const swimProducts: Product[] = [
  { id:"piscine-01", articleNumber:"PIS-0001", name:{fr:"Frozen · lunettes de natation violettes",en:"Frozen · purple swim goggles"}, category:"piscine", brand:"Disney Frozen", price:0, priceQc:0, priceConakry:0, stockQc:1, stockConakry:1, visibleQc:true, visibleConakry:true, ages:"3+", sheet:"", position:0, imageUrl:"/products/piscine/piscine-01.webp", status:"available", badge:"new", detail:{fr:"Lunettes de natation pour enfant sur le thème de La Reine des neiges.",en:"Kids swim goggles featuring Disney Frozen."} },
  { id:"piscine-02", articleNumber:"PIS-0002", name:{fr:"Frozen Elsa · lunettes de natation",en:"Frozen Elsa · swim goggles"}, category:"piscine", brand:"Disney Frozen", price:0, priceQc:0, priceConakry:0, stockQc:1, stockConakry:1, visibleQc:true, visibleConakry:true, ages:"3+", sheet:"", position:0, imageUrl:"/products/piscine/piscine-02.webp", status:"available", badge:"new", detail:{fr:"Lunettes de natation pour enfant avec motif Elsa.",en:"Kids swim goggles featuring Elsa."} },
  { id:"piscine-03", articleNumber:"PIS-0003", name:{fr:"Frozen · lunettes de natation bleues",en:"Frozen · blue swim goggles"}, category:"piscine", brand:"Disney Frozen", price:0, priceQc:0, priceConakry:0, stockQc:1, stockConakry:1, visibleQc:true, visibleConakry:true, ages:"3+", sheet:"", position:0, imageUrl:"/products/piscine/piscine-03.webp", status:"available", badge:"new", detail:{fr:"Lunettes de natation bleues pour enfant sur le thème Frozen.",en:"Blue kids swim goggles featuring Frozen."} },
  { id:"piscine-04", articleNumber:"PIS-0004", name:{fr:"Spider-Man · lunettes de natation",en:"Spider-Man · swim goggles"}, category:"piscine", brand:"Marvel Spider-Man", price:0, priceQc:0, priceConakry:0, stockQc:1, stockConakry:1, visibleQc:true, visibleConakry:true, ages:"3+", sheet:"", position:0, imageUrl:"/products/piscine/piscine-04.webp", status:"available", badge:"new", detail:{fr:"Lunettes de natation pour enfant inspirées de Spider-Man.",en:"Kids swim goggles inspired by Spider-Man."} },
  { id:"piscine-05", articleNumber:"PIS-0005", name:{fr:"Marvel Mini Heroes · lunettes rouge et bleu",en:"Marvel Mini Heroes · red and blue swim goggles"}, category:"piscine", brand:"Marvel", price:0, priceQc:0, priceConakry:0, stockQc:1, stockConakry:1, visibleQc:true, visibleConakry:true, ages:"3+", sheet:"", position:0, imageUrl:"/products/piscine/piscine-05.webp", status:"available", badge:"new", detail:{fr:"Lunettes de natation rouge et bleu pour enfant, collection Marvel Mini Heroes.",en:"Red and blue kids swim goggles from Marvel Mini Heroes."} },
  { id:"piscine-06", articleNumber:"PIS-0006", name:{fr:"Marvel Iron Man · lunettes de natation",en:"Marvel Iron Man · swim goggles"}, category:"piscine", brand:"Marvel Iron Man", price:0, priceQc:0, priceConakry:0, stockQc:1, stockConakry:1, visibleQc:true, visibleConakry:true, ages:"3+", sheet:"", position:0, imageUrl:"/products/piscine/piscine-06.webp", status:"available", badge:"new", detail:{fr:"Lunettes de natation rouge et jaune pour enfant sur le thème Iron Man.",en:"Red and yellow kids swim goggles featuring Iron Man."} },
  { id:"piscine-07", articleNumber:"PIS-0007", name:{fr:"Justice League · lunettes de natation",en:"Justice League · swim goggles"}, category:"piscine", brand:"DC Justice League", price:0, priceQc:0, priceConakry:0, stockQc:1, stockConakry:1, visibleQc:true, visibleConakry:true, ages:"3+", sheet:"", position:0, imageUrl:"/products/piscine/piscine-07.webp", status:"available", badge:"new", detail:{fr:"Lunettes de natation pour enfant de la collection Justice League.",en:"Kids swim goggles from the Justice League collection."} },
  { id:"piscine-08", articleNumber:"PIS-0008", name:{fr:"Marvel Mini Heroes · lunettes bleues",en:"Marvel Mini Heroes · blue swim goggles"}, category:"piscine", brand:"Marvel", price:0, priceQc:0, priceConakry:0, stockQc:1, stockConakry:1, visibleQc:true, visibleConakry:true, ages:"3+", sheet:"", position:0, imageUrl:"/products/piscine/piscine-08.webp", status:"available", badge:"new", detail:{fr:"Lunettes de natation bleues pour enfant, collection Marvel Mini Heroes.",en:"Blue kids swim goggles from Marvel Mini Heroes."} },
];
